name: glove_reader
description: Reads a glove with esp32 controller and IMUs
publish_to: "none"

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter_blue: ^0.7.2
  csv: ^4.0.3
  path_provider: ^0.4.1
  permission_handler: ^5.0.1
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  e2e: ^0.2.1
  flutter_driver:
    sdk: flutter

flutter:
  uses-material-design: true
